version: '3.1'

services:

  db:
    image: postgres
    build:
      context: .
      dockerfile: ./Dockerfile    
    restart: always
    environment:
      POSTGRES_PASSWORD: querycpp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
