def build(bld):

    bld(features = 'cxx cxxprogram',
        target = 'test_database_data_types',
        source = 'test_database_data_types.cpp',
        use = ['querycpp-test-includes', 'querycpp', 'gtest']
    )
